#!/usr/bin/env python3

import sys, time
from daemon import Daemon

class myDaemon(Daemon):
    def run(self):
        count = 0
        while True:
            time.sleep(1)
            count += 1
            print(f"The count is: {count}")

if __name__ == "__main__":
    daemon= myDaemon('/tmp/daemon-example.pid')
    if( len(sys.argv) == 2):
        if 'start' == sys.argv[1]:
            daemon.start()
        elif 'stop' == sys.argv[1]:
            daemon.stop()
        elif 'restart' == sys.argv[1]:
            daemon.restart()
        else:
            print("Unknown command")
            sys.exit(2)
        sys.exit(0)
    else:
        print(f"Usage {sys.argv[0]} start|stop|restart")
        sys.exit(2)